### PR TITLE
styling drop shift button from workers view

### PR DESCRIPTION
**Pull request by saradotlog**
## What type of PR is this? (check all applicable)

- [] Feature
- [] Refactor
- [] Bug Fix
- [x] Optimization
- [] Documentation Update
- [] Other (describe: )

## Description of what PR does
It adds the same styling as the shifts page to the drop shift button in the "view assigned shifts" workers view

Screenshot 2021-04-30 at 18 32 30

Shifts view:
Screenshot 2021-04-30 at 18 32 44

## Related PRs and/or Issues (if any)
- Step 6 https://github.com/OurTimeForTech/shiftwork2/issues/10
-

## QA Instructions, Screenshots, Recordings
It can be seen at http://localhost:3000/workers/id

## Added tests?

- [ ] yes
- [x] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [ ] No documentation needed

### CODE REVIEW

**Review by GabrielleEaston — APPROVED** [review]
Easy! @saradotlog

**Comment by msarit** [comment]
resolve conflicts, @saradotlog and I will merge 👍🏾

**Review by msarit — APPROVED** [review]

**Comment by msarit** [comment]
@saradotlog Hey Sara! Merging this branch was okay this time, but please leave the merging to me 🙏🏾 😄

**Comment by saradotlog** [comment]
@aritamana Oops, sorry! 🤦🏻‍♀️ Won't do it again 😖

**Comment by msarit** [comment]
no worries!

**Pull request merged**
