### PR TITLE
Tests For Shifts Controller

### PR DESCRIPTION
**Pull request by Timilehin08**
## What type of PR is this? (check all applicable)

- [] Feature
- [] Refactor
- [] Bug Fix
- [] Optimization
- [] Documentation Update
- [] Other (describe: )

## Related PRs and/or Issues (if any)
-
-

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [ ] No documentation needed

### CODE REVIEW

**Comment by Timilehin08** [comment]
@msarit I'm having an error pop up and this is why. for the redirect path, what the routes show me where it terminates, is different from what the shifts rb file says. I need clarity on that.

Also I saw that PATCH and PUT are doing the same function of 'update' in the route, so i incorporated only the PATCH. I'll like to  know if I am wrong in doing that.

**Comment by ncbui** [comment]
> Hello @msarit. I'm having an error pop up and this is why. for the redirect path, what the routes show me where it terminates, is different from what the shifts rb file says. I initially implemented what the route path says and the test still didn't pass. Same with when i used the path the shifts.rb file shows. I still had no luck on that. I'll really ike to know where i'm getting it wrong, as i got stuck.
> 
Hey @Timilehin08 , I think I ran into something similar. Are you getting an error message like this? 
Screen Shot 2021-05-12 at 4 39 38 AM

**Comment by Timilehin08** [comment]
Yes @ncbui that’s the same error I had. 
I’ll try out what you did for shift path and see if it works.

**Comment by msarit** [comment]
Hello @Timilehin08! 👋🏾 

So I decided to create some tutorials on how you can improve your tests.

The tutorial was long, so I divided it into 3 parts to be easier to manage bandwidth-wise 😅 

Part 1 of 3: https://www.loom.com/share/23fd75a0a7b04865ae6da08599085338
Part 2 of 3: https://www.loom.com/share/100bd2556b0e4a5c949b33c1c9d84d71
Part 3 of 3: https://www.loom.com/share/780542d640af40c9a6524df7c8a0435a?sharedAppSource=personal_library

I also created a gist of all the code I wrote in the tutorial, so you have easy access for copy-paste needs ❤️  

Gist: https://gist.github.com/msarit/adf9dcd8550df335d9e97e7b741616a1

**Pull request merged**
