### PR TITLE
New Organizations View UI

### PR DESCRIPTION
**Pull request by ncbui**
## What type of PR is this? (check all applicable)

- [] Feature
- [] Refactor
- [] Bug Fix
- [x] Optimization
- [] Documentation Update
- [] Other (describe: )

## Description of what PR does
This PR adds classes to style the New Organizations form.

## Related PRs and/or Issues (if any)
- Completes Task 2 in #12. 

## QA Instructions, Screenshots, Recordings
Pull this into your local environment and go to http://127.0.0.1:3000/

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ x ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [ ] No documentation needed

### CODE REVIEW

**Review by Timilehin08 — COMMENTED** [review]
Looks good to me! Welldone! @ncbui 

a quick question though? are we going to incorporate the ability to delete an account, either worker or organization? just the same way we can create and edit?

**Comment by Timilehin08** [comment]
Oh not to bother, I just remembered it's part of details included in the UI tasks break down.

**Review by msarit — APPROVED** [review]
Look great!

**Review by GabrielleEaston — APPROVED** [review]
Great work! @ncbui 😊

**Pull request merged**
