### PR TITLE
Building Out the rest of Shift functionality 😅

### PR DESCRIPTION
**Pull request by msarit**
## What type of PR is this? (check all applicable)

- [X] Feature
- [X] Refactor
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (describe: )

## Description of what PR does
This PR does the following:
- implements the `flatpickr` [tool](https://flatpickr.js.org/) to enable organizations to choose the start and end date-and-time for their shifts using a UX-friendly calendar picker. 
- ensures that shift times are displayed in user's chosen timezone, but stored in the database in UTC
- ensures that organizations cannot set a shift end-date before the shift start-date
- ensures that organizations create shifts of at least 1 hour
- ensures that a worker cannot drop a shift once the start-date-time is within 24 hours
- improves several related aspects of the application (eg link to worker assigned to shift)
- redirects organizations who hit `/shifts/` to their org#show page (which lists their own shifts). Keep the `/shifts` endpoint strictly for workers.
- refactors some areas (eg removes `@worker_bio` and just calls `@worker.bio`)
- ~Add number of completed shifts to worker's show page (as seen by organizations)~ (decided this was superfluous)
- fades alerts after 5 seconds
- other things I cannot think of now 😆  

## QA Instructions, Screenshots, Recordings
- Log in to app as both organization and worker (in seperate tabs) and play around with creating shifts.
- Create some shifts that start within 24 hours; next, take these shifts as a worker.
- Then, try to drop them - you shouldn't be able to.
- As an org, navigate to `/shifts`. You should be redirected to your `/organizations/:id` page.
- As an org, try to create shifts that are either less than 1 hour, or where the end occurs before the start. You should get the appropriate errors, and see that the create or edit form is re-rendered.

## Added tests?

- [X] yes, for the user parts; tests for shifts will be done by another team member.
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [X] No documentation needed

### CODE REVIEW

**Comment by GabrielleEaston** [comment]
@msarit I am still reviewing and studying your PR. Thank you for implementing the calendar picker and finishing the shifts feature. Thanks for adding the shift duration, per hour to pay, time zone (wow) and fade effect to the alerts. I ran into the error when I was trying to edit the shifts as org and didn't change the start & end times.

**Comment by GabrielleEaston** [comment]
Here is the
Here is the video to showcase what I am saying 😅


https://user-images.githubusercontent.com/48966654/117085011-adb2e400-ad16-11eb-90d1-8f2b60c79a28.mov

**Comment by msarit** [comment]
@GabrielleEaston Hey! Your observation is correct - unfortunately, I tried and tried to populate the date fields with the current dates when editing a shift, but it wouldn't work 🤷🏾‍♀️  So when editing, you HAVE to re-enter the dates again - which is why I displayed the current dates as a placeholder

I think a paragraph above the form to explain would help?

**Comment by GabrielleEaston** [comment]
@msarit I think the paragraph will make it clear!!! 😁

**Comment by msarit** [comment]
I'm merging this PR because whoever is working on the specs for Shifts will need the updates in this PR 😅

**Pull request merged**
