### PR TITLE
Custom 404 and 505 pages

### PR DESCRIPTION
**Pull request by Timilehin08**
## What type of PR is this? (check all applicable)

- [] Feature
- [] Refactor
- [] Bug Fix
- [x] Optimization
- [] Documentation Update
- [x] Other (describe: Styling)

## Description of what PR does

- Removed 404 and 505 html file in Public folder and Generate a new ErrorsController that inherits from ApplicationController with command `rails g controller errors not_found internal_server_error.`
- Configure Routes to Handle New Errors Page in `config/routes.rb.`
- Adjust configuration to turn off the default way Rails will handle errors in the main `application.rb` file.
- Disable configuration in `config/environments/development.rb` in order to test things out locally.
- Style, edit and adjust the views within `app/views/errors` accordingly.

## Related PRs and/or Issues (if any)
- #24 
-

## QA Instructions, Screenshots, Recordings
For example, go to http://127.0.0.1:3000/sss to see how error page looks like.
https://web-crunch.com/posts/custom-error-page-ruby-on-rails
## Added tests?

- [ ] yes
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [x] No documentation needed

### CODE REVIEW

**Comment by ncbui** [comment]
Hey @Timilehin08 , thanks for requesting review!
When I go to organizations#index, which isn't implemented, I see this streamlined, very bootstrappy page. Nice work! 
Screen Shot 2021-05-03 at 10 40 45 AM

But I'm also getting an odd message when I go to organizations#show for an org id that doesn't exist. This used to trigger rails' built-in 404 page but now looks like this. 
Screen Shot 2021-05-03 at 10 41 53 AM

**Comment by msarit** [comment]
@Timilehin08 Hey Timi! Please resolve the conflicts, and I will review the work you've done. Seeing as [25 files have been changed](https://github.com/OurTimeForTech/shiftwork2/pull/79/files) (😅 ) I think that high number is due to the conflicts.

**Comment by Timilehin08** [comment]
Hello @aritamana @ncbui @saradotlog @GabrielleEaston I resolved the conflicts already. A large part of The files changed is due to the my branch not been as recent as the main but apart from that, the conflicts have been resolved with main. 

I however still have issues with the 500 page showing the correct error message given. i tried to break the app and it showed the 500 error but not the styling and message put in the html folder. 
i'll try and send a screenshot as soon as i can.

**Comment by Timilehin08** [comment]
Hello @aritamana @ncbui @saradotlog @GabrielleEaston I resolved the conflicts already. A large part of The files changed is due to the my branch not been as recent as the main but apart from that, the conflicts have been resolved with main. 

I however still have issues with the 500 page showing the correct error message given. i tried to break the app and it showed the 500 error but not the styling and message put in the html folder. 
i'll try and send a screenshot as soon as i can but we can go ahead to review it when we can.

**Comment by Timilehin08** [comment]
Hello @aritamana @ncbui @saradotlog @GabrielleEaston I resolved the conflicts already. A large part of The files changed is due to the my branch not been as recent as the main but apart from that, the conflicts have been resolved with main. 

I however still have issues with the 500 page showing the correct error message given. i tried to break the app and it showed the 500 error but not the styling and message put in the html folder. 
i'll try and send a screenshot as soon as i can but we can go ahead to review it when we can.

**Comment by Timilehin08** [comment]
Hello @aritamana @ncbui @saradotlog @GabrielleEaston I resolved the conflicts already. A large part of The files changed is due to the my branch not been as recent as the main but apart from that, the conflicts have been resolved with main. 

I however still have issues with the 500 page showing the correct error message given. i tried to break the app and it showed the 500 error but not the styling and message put in the html folder. 
i'll try and send a screenshot as soon as i can but we can go ahead to review it when we can.

**Comment by Timilehin08** [comment]
Hello @ncbui. The error you mentioned here which is the 500 page has been resolved by #116.

**Comment by Timilehin08** [comment]
Hello @aritamana. Been on this since Thursday and I have to close this PR as it became way too difficult to resolve conflicts on that branch despite using git rebase --main into the branch. It was adding way more commits, almost 170, and not rebasing properly even after a conflict has been resolved. This is why i decided to create another branch today and PR which is #116.

**Pull request closed without merging**
